spring.application.name=hotel
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=123
spring.server=8080
spring.jpa.show-sql=true
# JWT
jwt.secret=MySuperSecretKeyForJwtTokenGenerationMustBeLongEnough123456
jwt.expiration=86400000

# ????????? CSRF ??? REST API
spring.security.csrf.disabled=true